version: '3.8'
services:
  app:
    extends:
      file: docker-compose-gateway-base.yml
      service: app
    container_name: gateway-prod
    ports:
      - "8113:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka:8761/eureka/
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 3G
    networks:
      - nervus-network

networks:
  nervus-network:
    external: true