version: '3.8'
services:
  app:
    image: ghcr.io/nervus-tech/nervus-gateway:${TAG}
    environment:
      - SERVER_PORT=8080
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=true
      - EUREKA_CLIENT_FETCH_REGISTRY=true
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 1G
    networks:
      - nervus-network