name: CI Pipeline - Gateway Service

on:
  push:
    branches: [main, develop, feature/*]
  pull_request:
    branches: [main, develop, feature/*]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    
    services:
      eureka:
        image: ghcr.io/nervus-tech/nervus-eureka-server:v1.0.0
        ports:
          - 8761:8761

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven
        run: mvn clean install -f gateway/pom.xml -DskipTests

      - name: Run Tests (if test files exist)
        run: |
          # Check if test files exist before running tests
          if [ -d "gateway/src/test" ] && [ "$(ls -A gateway/src/test)" ]; then
            mvn test -f gateway/pom.xml
          else
            echo "⚠️ No test files found, skipping tests"
          fi

      - name: Build Docker Image
        run: |
          cd gateway
          docker build -t ghcr.io/nervus-tech/nervus-gateway:${{ github.sha }} .
          docker tag ghcr.io/nervus-tech/nervus-gateway:${{ github.sha }} ghcr.io/nervus-tech/nervus-gateway:latest

      - name: Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/nervus-tech/nervus-gateway:${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          vuln-type: 'os,library'
          ignore-unfixed: true

      - name: Upload Trivy Scan Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Test Docker Container
        run: |
          cd gateway
          docker run -d --name test-container -p 8080:8080 \
            -e SPRING_PROFILES_ACTIVE=local \
            -e SERVER_PORT=8080 \
            -e EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://localhost:8761/eureka/ \
            -e EUREKA_CLIENT_REGISTER_WITH_EUREKA=true \
            -e EUREKA_CLIENT_FETCH_REGISTRY=true \
            -e EUREKA_INSTANCE_PREFER_IP_ADDRESS=true \
            ghcr.io/nervus-tech/nervus-gateway:${{ github.sha }}
          sleep 20
          curl -f http://localhost:8080/actuator/health || exit 1
          docker stop test-container
          docker rm test-container

      - name: Push to Registry (on main/develop)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        run: |
          echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/nervus-tech/nervus-gateway:${{ github.sha }}
          docker push ghcr.io/nervus-tech/nervus-gateway:latest
